config/routes.rb
MultiSiteSurveyApp::Application.routes.draw do
  resources :surveys do
    resources :questions
  end
  root :to => redirect('/surveys')
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  validates :survey, :question_text, :presence => true
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :questions
  validates :title, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_filter :find_survey!
	def index
		@questions = @survey.questions
	end

  def new
  end

  def create
    @question = Question.new(question_params.merge(:survey => @survey))
    if @question.save!
      flash[:notice] = "Question was successully created."
      redirect_to survey_questions_path
    else
      # Put warning message here
      render 'new'
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    @updated_question = question_params.merge(:survey => @survey)
    if @question.update_attributes!(@updated_question)
      flash[:notice] = "Update Successful."
    else
      flash[:notice] = "Update Failed"
    end 
    redirect_to survey_questions_path
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    flash[:notice] = "Question deleted in '#{@survey.title}'."
    redirect_to survey_questions_path
  end

  private
  def find_survey!
    @survey =  Survey.find(params[:survey_id])
  end
  def question_params
    params.require(:question).permit(:question_text,:question_type,:answer_options)
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

	def index
		@surveys = Survey.all
	end

	def show
		id = params[:id] # get survey from URL
		@survey = Survey.find(id)
	end

  def new
    #default: render 'new' template
  end

  def create
    @survey = Survey.new(survey_params)
    if @survey.save
      flash[:notice] = "#{@survey.title} was successully created."
      redirect_to surveys_path
    else
      flash[:warning] = "Title cannot be empty"
      render 'new'
    end
  end

  def edit
    @survey = Survey.find(params[:id])
  end
  def update
    @survey = Survey.find(params[:id])
    if @survey.update_attributes!(survey_params)
      flash[:notice] = "Update Successful"
    else
      flash[:warning] = "Update Failed"
    end
    redirect_to surveys_path
  end

  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy
    flash[:notice] = "survey '#{@survey.title}' deleted."
    redirect_to surveys_path
  end


private
def survey_params
  params.require(:survey).permit(:title)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title SurveyBuilder
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags
 
  %body
    -# this goes just inside %body:
    - if flash[:notice]
      #notice.message= flash[:notice]
    - elsif flash[:warning]
      #warning.message= flash[:warning]

    #main
      = yield

app/views/questions/edit.html.haml
%h2 Edit Question in '#{@survey.title}'

= form_tag survey_question_path(@survey,@question), :method => :put do

  %table#editquestion
    
    %tbody
      %tr
        %td= label :question, :question_text, 'Enter Question'
        %td= text_field :question, :question_text
      %tr
        %td= label :question, :question_type, 'Question Type'   
        %td= select :question, :question_type,['Text','CheckBox', 'Radio']
      %tr
        %td= label :question, :answer_options, 'Answer Options'   
        %td= text_area :question, :answer_options,rows: 5
      %tr
        %td   
        %td= submit_tag 'Update'
        
%br
= link_to  'Back to Survey', survey_questions_path

app/views/questions/index.html.haml
%h2 Survey Editor : #{@survey.title}
%p= link_to 'Add Questions',new_survey_question_path(@survey)
%h3 Questions
%table#questions
  %thead
    %tr
      %th                               
      %th 
      %th 
  %tbody
    - @questions.each do |question|
      %tr
        %td= question.question_text
        %td= link_to "Edit", edit_survey_question_path(@survey,question) 
        %td= link_to "Delete", survey_question_path(@survey,question), :method => :delete

%br
= link_to  'Back to Home Page', surveys_path

app/views/questions/new.html.haml
%h2 Add New Question

= form_tag survey_questions_path, :method => :post do

  %table#newquestion
    
    %tbody
      %tr
        %td= label :question, :question_text, 'Enter Question'
        %td= text_field :question, :question_text
      %tr
        %td= label :question, :question_type, 'Question Type'   
        %td= select :question, :question_type,['Text','CheckBox', 'Radio']
      %tr
        %td= label :question, :answer_options, 'Answer Options'   
        %td= text_area :question, :answer_options,rows: 5
      %tr
        %td   
        %td= submit_tag 'Create'
        
%br
= link_to  'Back to Survey', survey_questions_path

app/views/surveys/edit.html.haml
%h2 Edit #{@survey.title}

= form_tag survey_path(@survey), :method => :put do

  %table#editsurvey
    
    %tbody
      %tr
        %td= label :survey, :title, 'Title'
        %td= text_field :survey, :title
               

      %tr
        %td   
          -#%button#addquestion{:onclick => "addquestion()", :type => "button"} Add Question
        %td= submit_tag 'Update'
        
%br
= link_to  'Back to Home Page', surveys_path
  

app/views/surveys/index.html.haml
-#  Home page for MultiSiteSurveyApp
%h2 Welcome to the Survey Builder
%p= link_to 'Create a new Survey',new_survey_path
%h3 List of Surveys
%table#surveys
  %thead
    %tr
      %th Title
      %th 
      %th 
  %tbody
    - @surveys.each do |survey|
      %tr
        %td= link_to survey.title, survey_questions_path(survey)
        %td= link_to "Edit", edit_survey_path(survey)
        %td= link_to "Delete",survey_path(survey), :method => :delete

app/views/surveys/new.html.haml
%h2 Create New Survey

= form_tag surveys_path, :method => :post do

  %table#newsurvey
    
    %tbody
      %tr
        %td= label :survey, :title, 'Title'
        %td= text_field :survey, :title
               

      %tr
        %td   
          -#%button#addquestion{:onclick => "addquestion()", :type => "button"} Add Question
        %td= submit_tag 'Save Changes'
        
%br
= link_to  'Back to Home Page', surveys_path
  

app/views/surveys/show.html.haml
%h2 #{@survey.title}
%br
= link_to  'Back to Home Page', surveys_path